name: 🐛 Bug Report
labels: ["bug", "untriaged"]
description: Report unexpected behavior or errors.
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behavior in the existing issues.
        
        ---
  - type: textarea
    id: describe-problem
    attributes:
      label: Describe the problem
      description:
        Describe the issue you are experiencing. Provide a clear and concise description of what you were trying to do and what happened, including any error messages you encountered.
    validations:
      required: true
  - type: input
    id: library-version
    attributes:
      label: Library version
      description:
        Specify the version of the library you are using.
    validations:
      required: true
  - type: input
    id: powerbi-version
    attributes:
      label: Power BI version
      description:
        Specify the version of Power BI Desktop or Service you are using.
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: List the steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. ...
        4. See the error
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description:
        Add any other relevant context about the issue here.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain your problem, if applicable.

